import {StyleSheet} from 'react-native';
import {Fonts, mainColors} from '../../../contants';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
export const styles = StyleSheet.create({
  styleModal: {
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  container: {
    width: wp(100),
    paddingTop: hp(3),
    height: wp(100) * 0.841982235,
  },
  nameFoodModal: {
    color: mainColors.blackColor,
    fontFamily: Fonts.Roboto_Stab_Bold,
    fontSize: wp(4),
    width: '60%',
  },
  titleModal: {
    fontSize: wp(4),
    color: mainColors.blackColor,
    fontFamily: Fonts.Roboto_Slab_Regular,
  },
  viewImageModal: {
    width: wp(26),
    height: wp(28),
    borderWidth: 4,
    borderColor: mainColors.whiteColor,
    overflow: 'hidden',
    borderRadius: wp(2),
    zIndex: 999,
    position: 'absolute',
  },
  viewSllModal: {
    marginTop: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: mainColors.blackColor,
    paddingHorizontal: wp(2),
    borderRadius: wp(1),
    paddingVertical: wp(0.5),
    marginStart: wp(4),
    backgroundColor: mainColors.whiteColor,
  },

  controlSll: {
    fontSize: wp(5),
    fontFamily: Fonts.Roboto_Stab_Bold,
  },
  sllText: {
    fontSize: wp(4),
    color: mainColors.blackColor,
    marginHorizontal: wp(2),
    fontFamily: Fonts.Roboto_Stab_Bold,
  },
  hitSlopSll: {
    top: 5,
    bottom: 5,
    left: 5,
    right: 5,
  },
  viewRowItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(1),
  },
  rowSpaceBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(5),
  },
  sizeView: {
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: mainColors.blackColor,
    borderRadius: wp(2),
    paddingVertical: wp(1),
    marginStart: wp(2.5),
    paddingHorizontal: wp(2),
    backgroundColor: mainColors.whiteColor,
  },
  sizeTitle: {
    fontFamily: Fonts.Roboto_Slab_Light,
    color: mainColors.blackColor,
    fontSize: wp(4),
  },
  btnOrder: {
    alignItems: 'center',
    paddingVertical: hp(0.8),
    borderRadius: wp(1),
    marginTop: hp(1),
    marginBottom: hp(1.5),
    marginHorizontal: wp(1.5),
    backgroundColor: mainColors.whiteColor,
  },
  viewImgItem: {
    width: wp(25),
    height: hp(13),
    borderWidth: 2,
    borderColor: mainColors.mainColor,
  },
  menuInfoView: {
    width: wp(65),
    height: wp(65) * 0.20674698795,
    marginLeft: 1,
    justifyContent: 'center',
    paddingLeft: wp(6),
  },
  textInfoMenu: {
    fontFamily: Fonts.Roboto_Slab_Regular,
    fontSize: wp(3.2),
    color: '#000',
    width: '70%',
  },
  line: {
    height: 1.5,
    width: wp(40),
    backgroundColor: mainColors.blackColor,
    marginVertical: hp(0.5),
    marginLeft: wp(0.5),
  },
  viewSll: {
    width: wp(26),
    height: wp(26) * 0.196460177,
    marginLeft: wp(0.5),
    alignItems: 'center',
    justifyContent: 'center',
    paddingRight: wp(3),
  },
  textInputStyle: {
    borderColor: '#000',
    borderWidth: 1,
    padding: 0,
    paddingLeft: wp(2),
    backgroundColor: '#F0EFEF',
    color: '#000',
    fontFamily: Fonts.Roboto_Slab_Regular,
    borderRadius: wp(2),
  },
  overFood: {
    fontFamily: Fonts.Roboto_Slab_Regular,
    fontSize: wp(3),
    color: mainColors.whiteColor,
  },
  viewRowNormal: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  viewSize: {
    width: wp(20),
    height: wp(20) * 0.266666667,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
