export const DummyListDish = [
  {
    meal: 'Gà chiên nước mắm',
    sllWait: '0',
    sllComplete: '4',
    sllCancel: '0',
    price: '360.000Đ',
    status: 'Hoàn thành',
  },
  {
    meal: 'Gỏi xoài tôm khô',
    sllWait: '0',
    sllComplete: '3',
    sllCancel: '0',
    price: '210.000Đ',
    status: 'Hoàn thành',
  },
  {
    meal: 'Gỏi chân gà rút xương',
    sllWait: '0',
    sllComplete: '4',
    sllCancel: '0',
    price: '260.000Đ',
    status: 'Hoàn thành',
  },
  {
    meal: 'Súp gà xé',
    sllWait: '0',
    sllComplete: '4',
    sllCancel: '0',
    price: '120.000Đ',
    status: 'Hoàn thành',
  },
  {
    meal: 'Súp cua',
    sllWait: '0',
    sllComplete: '4',
    sllCancel: '0',
    price: '230.000Đ',
    status: 'Hoàn thành',
  },
  {
    meal: 'Cà tím nướng',
    sllWait: '2',
    sllComplete: '4',
    sllCancel: '0',
    price: '350.000Đ',
    status: 'Đang đợi',
  },
  {
    meal: 'Rau mốp xào tỏi',
    sllWait: '1',
    sllComplete: '4',
    sllCancel: '1',
    price: '90.000Đ',
    status: 'Đang đợi',
  },
  {
    meal: 'Gà chiên me',
    sllWait: '2',
    sllComplete: '4',
    sllCancel: '1',
    price: '150.000Đ',
    status: 'Đang đợi',
  },
  {
    meal: 'Cải bó xôi xào tỏi',
    sllWait: '1',
    sllComplete: '4',
    sllCancel: '1',
    price: '120.000Đ',
    status: 'Đang đợi',
  },
  {
    meal: 'Ếch nướng muối ớt',
    sllWait: '0',
    sllComplete: '1',
    sllCancel: '1',
    price: '360.000Đ',
    status: 'Đã huỷ',
  },
  {
    meal: 'Lẩu cá diêu hồng',
    sllWait: '0',
    sllComplete: '1',
    sllCancel: '1',
    price: '250.000Đ',
    status: 'Đã huỷ',
  },
  {
    meal: 'Nắm thập cẩm xào tỏi',
    sllWait: '0',
    sllComplete: '4',
    sllCancel: '4',
    price: '120.000Đ',
    status: 'Đã huỷ',
  },
];
export const DataTable = [
  [{key: 'Bàn 1'}, {key: 'Bàn 2'}, {key: 'Bàn 3'}],
  [{key: 'Bàn 4'}, {key: 'Bàn 5'}],
  [{key: 'Bàn 7'}, {key: 'Bàn 8'}, {key: 'Bàn 9'}],
  [{key: 'Bàn 10'}, {key: 'Bàn 11'}],
  [{key: 'Bàn 7'}, {key: 'Bàn 8'}, {key: 'Bàn 9'}],
  [{key: 'Bàn 10'}, {key: 'Bàn 11'}],
  [{key: 'Bàn 7'}, {key: 'Bàn 8'}, {key: 'Bàn 9'}],
  [{key: 'Bàn 10'}, {key: 'Bàn 11'}],
];
